name: NPM Trusted Publisher

on:
  workflow_call:
    secrets:
      GIT_TOKEN:
        description: 'github personal token'
        required: true

    inputs:
      dry_run:
        type: boolean
        description: pass dry-run to semantic-release
        default: false

      action_ref:
        type: string
        description: 'Branch name for node-modules/github-actions, for test purpose'
        default: master

      skip_build:
        type: boolean
        description: skip the build step prior to release
        default: false

jobs:
  Release:
    permissions:
      contents: write
      id-token: write # Required for OIDC
      deployments: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: main_repo

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      # Checkout action repository
      - name: Checkout action repository
        uses: actions/checkout@v5
        with:
          repository: node-modules/github-actions
          path: action_repo
          ref: ${{ inputs.action_ref }}

      # Checkout project repository
      - name: Checkout project repository
        uses: actions/checkout@v5
        with:
          path: main_repo
          token: ${{ secrets.GIT_TOKEN }}

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest
      
      - name: Install pnpm
        run: npm install -g pnpm

      # Install action dependencies
      - name: Install action dependencies
        run: pnpm install --no-frozen-lockfile
        working-directory: action_repo/scripts/npm-release

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: main_repo

      # Build the project
      - name: Build
        if: ${{ !inputs.skip_build }}
        run: pnpm run build
        working-directory: main_repo

      - name: Semantic Release
        id: release
        run: node ../action_repo/scripts/npm-release/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRYRUN: ${{ inputs.dryRun }}

      - name: Publish ${{ steps.release.outputs.name }}@${{ steps.release.outputs.release_version }}
        if: steps.release.outputs.release_version && !inputs.dryRun
        run: |
          echo ${{ steps.release.outputs.name }}
          echo ${{ steps.release.outputs.release_version }}
          echo ${{ steps.release.outputs.registry }}